spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
  application:
    name: BATCH
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update